# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Morglaf.HimaWeb
PackageVersion: 0.1.5.0
PackageLocale: en-US
Publisher: Morglaf
PackageName: HimaWeb
License: GPL
ShortDescription: HimaWeb Setup
ManifestType: defaultLocale
ManifestVersion: 1.12.0
