# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Morglaf.HimaWeb
PackageVersion: 0.1.5.0
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Morglaf/Himaweb/releases/download/v0.1.5/HimaWeb-Setup-x64.exe
  InstallerSha256: A6283C3FA3992895D307B67670AEFC4DC59973BF854B4796629037A9EADD63CD
ManifestType: installer
ManifestVersion: 1.12.0
